/*##### CLEANUP SCRIPT #####*/

-- Set role and context
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE;

-- Cleanup Snowflake objects
DROP DATABASE HOL_TIMESERIES;
DROP WAREHOUSE HOL_TRANSFORM_WH;
DROP WAREHOUSE HOL_ANALYTICS_WH;
DROP ROLE ROLE_HOL_TIMESERIES;
DROP USER USER_HOL_TIMESERIES;

/*##### CLEANUP SCRIPT #####*/