-- Setup Reporting Views
USE ROLE ROLE_HOL_TIMESERIES;
USE HOL_TIMESERIES.ANALYTICS;

-- Tag Reference View
CREATE OR REPLACE VIEW HOL_TIMESERIES.ANALYTICS.TS_TAG_REFERENCE AS
SELECT
    META.NAMESPACE,
    META.TAGNAME,
    META.TAGALIAS,
    META.TAGDESCRIPTION,
    META.TAGUNITS,
    META.TAGDATATYPE
FROM HOL_TIMESERIES.TRANSFORM.TS_TAG_METADATA META;

-- Review Tag Reference
SELECT * FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_REFERENCE;

-- Tag Readings View
CREATE OR REPLACE VIEW HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS AS
SELECT
    META.TAGNAME,
    READ.TS AS TIMESTAMP,
    READ.VAL AS VALUE,
    READ.VAL_NUMERIC AS VALUE_NUMERIC
FROM HOL_TIMESERIES.TRANSFORM.TS_TAG_METADATA META
INNER JOIN HOL_TIMESERIES.TRANSFORM.TS_TAG_READINGS READ
ON META.TAGKEY = READ.TAGKEY;

-- Review Tag Readings
SELECT * FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS;


-- Run Time Series Analysis across various query profiles

-- RAW DATA
SELECT tagname, timestamp, value
FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS
WHERE timestamp > '2000-03-26 12:45:37' 
AND timestamp <= '2024-04-26 14:45:37' 
AND tagname = '/IOT/SENSOR/100' 
ORDER BY tagname, timestamp
;

-- HI WATER
SELECT tagname, to_timestamp('2024-03-26 14:47:55') AS timestamp, MAX_BY(value, timestamp) AS value
FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS
WHERE timestamp > '2000-03-26 12:45:37' 
AND timestamp <= '2024-04-26 14:45:37' 
AND tagname = '/IOT/SENSOR/100'
GROUP BY tagname 
ORDER BY tagname, timestamp
;

-- LOW WATER
SELECT tagname, to_timestamp('2024-03-26 14:47:55') AS timestamp, MIN_BY(value, timestamp) AS value
FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS
WHERE timestamp > '2000-03-26 12:45:37' 
AND timestamp <= '2024-04-26 14:45:37' 
AND tagname = '/IOT/SENSOR/100'
GROUP BY tagname 
ORDER BY tagname, timestamp
;

-- DOWNSAMPLING / RESAMPLING

-- BINNING - PERCENTILE
SELECT tagname, TIME_SLICE(DATEADD(MILLISECOND, -1, timestamp), 10, 'SECOND', 'END') AS timestamp, APPROX_PERCENTILE(value_numeric, 0.5) AS value
FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS 
WHERE timestamp > '2000-03-26 12:45:37' 
AND timestamp <= '2024-04-26 14:45:37' 
AND tagname = '/IOT/SENSOR/100'
GROUP BY TIME_SLICE(DATEADD(MILLISECOND, -1, timestamp), 10, 'SECOND', 'END'), tagname 
ORDER BY tagname, timestamp
;

-- BINNING - AVERAGE
SELECT tagname, TIME_SLICE(DATEADD(MILLISECOND, -1, timestamp), 10, 'SECOND', 'END') AS timestamp, AVG(value_numeric) AS value, count(*) as reading_count
FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS 
WHERE timestamp > '2000-03-26 12:45:37' 
AND timestamp <= '2024-04-26 14:45:37' 
AND tagname = '/IOT/SENSOR/100'
GROUP BY TIME_SLICE(DATEADD(MILLISECOND, -1, timestamp), 10, 'SECOND', 'END'), tagname 
ORDER BY tagname, timestamp
;

-- FIRST_VALUE / LAST_VALUE
SELECT tagname, ts as timestamp, f_value, l_value
FROM (
SELECT tagname, TIME_SLICE(DATEADD(MILLISECOND, -1, timestamp), 10, 'SECOND', 'END') AS ts, timestamp, value_numeric, FIRST_VALUE(value_numeric) OVER (PARTITION BY tagname, ts ORDER BY timestamp) AS f_value, LAST_VALUE(value_numeric) OVER (PARTITION BY tagname, ts ORDER BY timestamp) AS l_value
FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS  
WHERE timestamp > '2000-03-26 12:45:37' 
AND timestamp <= '2024-04-26 14:45:37' 
AND tagname = '/IOT/SENSOR/100'
GROUP BY TIME_SLICE(DATEADD(MILLISECOND, -1, timestamp), 10, 'SECOND', 'END'), timestamp, tagname, value_numeric
)
GROUP BY tagname, ts, f_value, l_value
ORDER BY tagname, ts
;

-- STDDEV
SELECT tagname, TIME_SLICE(DATEADD(MILLISECOND, -1, timestamp), 10, 'SECOND', 'END') AS timestamp, STDDEV(value_numeric) AS value 
FROM HOL_TIMESERIES.ANALYTICS.TS_TAG_READINGS 
WHERE timestamp > '2000-03-26 12:45:37' 
AND timestamp <= '2024-04-26 14:45:37' 
AND tagname = '/IOT/SENSOR/100' 
GROUP BY TIME_SLICE(DATEADD(MILLISECOND, -1, timestamp), 10, 'SECOND', 'END'), tagname 
ORDER BY tagname, timestamp
;