USE ROLE ROLE_HOL_TIMESERIES;
USE HOL_TIMESERIES.ANALYTICS;

-- CREATE STAGE FOR STREAMLIT FILES
CREATE OR REPLACE STAGE HOL_TIMESERIES.ANALYTICS.STAGE_TS_STREAMLIT
DIRECTORY = (ENABLE = TRUE, REFRESH_ON_CREATE = TRUE); 

-- LIST STAGE FILES
LIST @HOL_TIMESERIES.ANALYTICS.STAGE_TS_STREAMLIT;

-- CREATE STREAMLIT APP
/*
CREATE OR REPLACE STREAMLIT hol_ts_streamlit
ROOT_LOCATION = '@HOL_TIMESERIES.ANALYTICS.STAGE_TS_STREAMLIT'
MAIN_FILE = '/1_TS_Home.py'
QUERY_WAREHOUSE = TIMESERIES_WH;
*/
-- Use Snowflake CLI to upload Streamlit app

-- STREAMLIT
SHOW STREAMLITS;

-- Query packages
SELECT * FROM HOL_TIMESERIES.INFORMATION_SCHEMA.PACKAGES
WHERE LANGUAGE = 'python'
AND PACKAGE_NAME ILIKE '%htb%';