-- Set role, context, and warehouse
USE ROLE ROLE_HOL_TIMESERIES;
USE SCHEMA HOL_TIMESERIES.STAGING;
USE WAREHOUSE HOL_TRANSFORM_WH;

-- Setup staging tables
-- IOTSTREAM
CREATE OR REPLACE TABLE HOL_TIMESERIES.STAGING.RAW_TS_IOTSTREAM_DATA (
    RECORD_METADATA VARIANT,
    RECORD_CONTENT VARIANT
)
CHANGE_TRACKING = TRUE
COMMENT = 'IOTSTEAM staging table.'
;

-- Setup stream change tracking
CREATE OR REPLACE STREAM HOL_TIMESERIES.STAGING.STREAM_RAW_TS_IOTSTREAM_DATA
ON TABLE HOL_TIMESERIES.STAGING.RAW_TS_IOTSTREAM_DATA
SHOW_INITIAL_ROWS = TRUE
;

/*
Configure the IOT Stream client
*/

-- SHOW STREAM CHANNELS
SHOW CHANNELS;