USE ROLE ROLE_HOL_TIMESERIES;
USE HOL_TIMESERIES.ANALYTICS;

-- CREATE STAGE FOR STREAMLIT FILES
CREATE OR REPLACE STAGE HOL_TIMESERIES.ANALYTICS.STAGE_TS_STREAMLIT
DIRECTORY = (ENABLE = TRUE, REFRESH_ON_CREATE = TRUE);

-- LIST STAGE FILES
LIST @HOL_TIMESERIES.ANALYTICS.STAGE_TS_STREAMLIT;

-- CREATE STREAMLIT APP
-- Use Snowflake CLI to upload Streamlit app

-- STREAMLIT
SHOW STREAMLITS;