-- Set role, context, and warehouse
USE ROLE ROLE_HOL_TIMESERIES;
USE HOL_TIMESERIES.TRANSFORM;
USE WAREHOUSE HOL_TRANSFORM_WH;

-- Setup Transform Tabls
-- Sensor metadata (Dimension)
CREATE OR REPLACE TABLE HOL_TIMESERIES.TRANSFORM.TS_TAG_METADATA (
    TAGKEY NUMBER NOT NULL,
    NAMESPACE VARCHAR,
    TAGNAME VARCHAR NOT NULL,
    TAGALIAS ARRAY,
    TAGDESCRIPTION VARCHAR,
    TAGUNITS VARCHAR,
    TAGDATATYPE VARCHAR,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    CONSTRAINT PK_TSD_TAG_METADATA PRIMARY KEY (TAGKEY) RELY
);

-- Sensor readings (Fact)
CREATE OR REPLACE TABLE HOL_TIMESERIES.TRANSFORM.TS_TAG_READINGS (
    TAGKEY NUMBER NOT NULL,
    TS TIMESTAMP_NTZ NOT NULL,
    VAL VARCHAR,
    VAL_NUMERIC FLOAT,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    CONSTRAINT FK_TSD_TAG_READINGS FOREIGN KEY (TAGKEY) REFERENCES HOL_TIMESERIES.TRANSFORM.TS_TAG_METADATA (TAGKEY) RELY
);

-- IOT STREAM Load
-- Transform and load raw IOT sensor metadata
INSERT INTO HOL_TIMESERIES.TRANSFORM.TS_TAG_METADATA
WITH NEWTAGS AS (
    SELECT DISTINCT
        SRC.RECORD_METADATA:headers:namespace::VARCHAR AS NAMESPACE,
        UPPER(CONCAT('/', SRC.RECORD_METADATA:headers:namespace::VARCHAR, '/', TRIM(SRC.RECORD_CONTENT:tagname::VARCHAR))) AS TAGNAME,
        SRC.RECORD_METADATA:headers:source::VARCHAR AS TAGDESCRIPTION,
        SRC.RECORD_CONTENT:units::VARCHAR AS TAGUNITS,
        SRC.RECORD_CONTENT:datatype::VARCHAR AS TAGDATATYPE
    FROM HOL_TIMESERIES.STAGING.RAW_TS_IOTSTREAM_DATA SRC
    WHERE NOT EXISTS (
        SELECT 1 FROM HOL_TIMESERIES.TRANSFORM.TS_TAG_METADATA TGT
        WHERE TGT.TAGNAME = UPPER(CONCAT('/', SRC.RECORD_METADATA:headers:namespace::VARCHAR, '/', TRIM(SRC.RECORD_CONTENT:tagname::VARCHAR)))
    )
)
SELECT
    (SELECT MAX(ZEROIFNULL(TAGKEY)) FROM HOL_TIMESERIES.TRANSFORM.TS_TAG_METADATA) + ROW_NUMBER() OVER (PARTITION BY NULL ORDER BY SRC.TAGNAME) AS TAGKEY,
    SRC.NAMESPACE AS NAMESPACE,
    SRC.TAGNAME AS TAGNAME,
    TO_ARRAY(SRC.TAGNAME) AS TAGALIAS,
    SRC.TAGDESCRIPTION AS TAGDESCRIPTION,
    SRC.TAGUNITS,
    SRC.TAGDATATYPE,
    SYSDATE() AS INGESTION_TIMESTAMP
FROM NEWTAGS SRC
ORDER BY TAGKEY, TAGNAME;

-- Transform and load raw IOT sensor Readings
INSERT INTO HOL_TIMESERIES.TRANSFORM.TS_TAG_READINGS
SELECT
    META.TAGKEY,
    SRC.RECORD_CONTENT:timestamp::VARCHAR::TIMESTAMP_NTZ AS TS,
    SRC.RECORD_CONTENT:value::VARCHAR AS VAL,
    TRY_CAST(SRC.RECORD_CONTENT:value::VARCHAR AS FLOAT) AS VAL_NUMERIC,
    SYSDATE() AS INGESTION_TIMESTAMP
FROM HOL_TIMESERIES.STAGING.RAW_TS_IOTSTREAM_DATA SRC
INNER JOIN HOL_TIMESERIES.TRANSFORM.TS_TAG_METADATA META ON META.TAGNAME = UPPER(CONCAT('/', SRC.RECORD_METADATA:headers:namespace::VARCHAR, '/', TRIM(SRC.RECORD_CONTENT:tagname::VARCHAR)))
WHERE NOT EXISTS (
    SELECT 1 FROM HOL_TIMESERIES.TRANSFORM.TS_TAG_READINGS TGT
    WHERE TGT.TAGKEY = META.TAGKEY AND TGT.TS = SRC.RECORD_CONTENT:timestamp::VARCHAR::TIMESTAMP_NTZ
)
ORDER BY TAGKEY, TS;

-- Setup streams and tasks
