# Streamlit in Snowflake
name: hol-timeseries-streamlit
channels:
  - snowflake
dependencies:
  - streamlit=1.26.0
  - streamlit-extras=0.2.7
  - altair=4.2.2
  - pandas=2.0.3
  - plotly=5.19.0
  - tsdownsample=0.1.3