# Streamlit in Snowflake
name: hol-timeseries-streamlit
channels:
  - snowflake
dependencies:
  - streamlit=1.44.1
  - streamlit-extras=0.6.0
  - altair=5.5.0
  - pandas=2.2.3
  - plotly=6.0.1
  - tsdownsample=0.1.3