/*##### ACCOUNT_IDENTIFIER SCRIPT #####*/

-- Login as ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Find your Snowflake ACCOUNT_IDENTIFIER details - <account_identifier>.snowflakecomputing.com
SELECT REPLACE(AL.VALUE:host::VARCHAR, '.snowflakecomputing.com', '') AS ACCOUNT_IDENTIFIER
FROM TABLE(FLATTEN(input => PARSE_JSON(SYSTEM$ALLOWLIST()))) AS AL
WHERE AL.VALUE:type::VARCHAR = 'SNOWFLAKE_DEPLOYMENT_REGIONLESS';

/*##### ACCOUNT_IDENTIFIER SCRIPT #####*/