# Local HOL
# Create: conda env create -f .devcontainer/codespace_environment.yml
# Activate: conda activate hol-timeseries
# Remove: conda remove -n hol-timeseries --all

name: hol-timeseries
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.11
  - snowflake-snowpark-python[secure-local-storage,pandas]=1.31.1
  - altair=4.2.2
  - pandas=2.0.3
  - setuptools=68.2.2
  - h5py=3.9.0
  - notebook=7.0.8
  - openpyxl=3.0.10
  - matplotlib=3.8.0
  - tsdownsample=0.1.3
  - pip
  - pip:
    - streamlit==1.45.0
    - streamlit-extras==0.6.0
    - snowflake-cli==3.8.3
    - pyarrow==18.1.0